version: "1.0"
stages:
  - prepare
  - apply
steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "cgdevops123/CFrepo3"
    revision: main
    git: "github"
    stage: prepare
  init:
    type: freestyle
    title: Applying Terraform
    working_directory: '${{CLONE_STEP_NAME}}'
    arguments:
      image: 'hashicorp/terraform:latest'
      commands:
        - terraform init
        - terraform apply -auto-approve
    stage: apply
    
    
